# .gitlab-ci.yml
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "-B"
  DOCKER_IMAGE: "host.docker.internal:4000/${CI_PROJECT_NAME}"
  DOCKER_TAG: "${CI_COMMIT_SHORT_SHA}"
  KUBE_NAMESPACE: "default"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - build
  - test
  - package
  - push
  - deploy

.maven_template:
  image: maven:3.9-eclipse-temurin-21
  cache:
    key:
      files:
        - pom.xml
    paths:
      - .m2/repository
    policy: pull-push

# BUILD
build:
  extends: .maven_template
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
      - target/
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_TAG

# TEST
test:
  extends: .maven_template
  stage: test
  needs: ["build"]
  services:
    - name: postgres:16-alpine
      alias: postgres
  variables:
    POSTGRES_DB: equipment_maintenance
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_password
    POSTGRES_HOST: postgres        # имя сервиса = хост
    POSTGRES_PORT: "5432"
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    paths:
      - target/surefire-reports/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_TAG

# PACKAGE (jar)
package:
  extends: .maven_template
  stage: package
  needs: ["test"]
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_TAG

# BUILD & PUSH
push:
  stage: push
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  needs: ["package"]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
      --destination "${DOCKER_IMAGE}:${DOCKER_TAG}"
      --destination "${DOCKER_IMAGE}:latest"
      --insecure
      --skip-tls-verify
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_TAG

# DEPLOY
deploy:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  needs: ["push"]
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl set image deployment/backend backend=$DOCKER_IMAGE:$DOCKER_TAG -n $KUBE_NAMESPACE
    - kubectl rollout status deployment/backend -n $KUBE_NAMESPACE
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: $CI_COMMIT_TAG
      when: manual