 apiVersion: v1
 kind: Service
 metadata:
   name: vlad-eq-backend
   namespace: default
 spec:
   selector:
     app: vlad-eq-backend
   ports:
     - port: 8080
       targetPort: 8080
   type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlad-eq-backend
  namespace: default
  labels:
    app: vlad-eq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vlad-eq
  template:
    metadata:
      labels:
        app: vlad-eq
    spec:
      containers:
        - name: vlad-eq
          image: localhost:4000/vlad_eq:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SPRING_DATASOURCE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15